### ISSUE TITLE
modal function not working on bootstrap 4.0.0-beta

### ISSUE THREAD

**Issue by towfiles** [twbs/bootstrap#24054]
TypeError: $(...).modal is not a function error after implementing the modal feature on bootstrap 4.0.0-beta 

- jquery with bootsrap loading sequence has been checked, everything is loading well
- jquery version 3.1.1

`$("#clickme").click(function (e) {
                    e.preventDefault;
                    $('#exampleModal').modal('show')

                })`

`<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New message</h5>
        <button type="button" class="close" data-dismiss="modal" aria-la    bel="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group">
            <label for="recipient-name" class="form-control-label">Recipient:</label>
            <input type="text" class="form-control" id="recipient-name" value="rsdftrtytrere">
          </div>
          <div class="form-group">
            <label for="message-text" class="form-control-label">Message:</label>
            <textarea class="form-control" id="message-text">dffgffgddssfdghjgfd</textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Send message</button>
      </div>
    </div>
  </div>
</div>`

`<a href="#" id="clickme"  class="btn btn-primary">Stock Category</a>`

- i fixed the issue by copying out the loaded bootstrap js and css file on bootstrap website for it to work

**Comment by towfiles** [comment]
well bootstrap was loaded after jquery, but the issue never changed until i changed the version of bootstrap

**Comment by Johann-S** [comment]
Please provide a reduce test case on Codepen

**Comment by wolfy1339** [comment]
First off, you have an error in your JavaScript `e.preventDefault` should be a function call

**Comment by msolimans** [comment]
I faced the same issue and I discovered issue was caused due to the use of latest version of popper (1.12.5). When I downgraded popper to version 1.11.0 it worked perfectly.

**Comment by Johann-S** [comment]
seems very strange @msolimans be sure to use the UMD dist of Popper.js

**Comment by jadvillafania** [comment]
I encountered this error too using bootstrap 4.0-beta.2 and popper 1.12.6. To solve the issue, I have to use this declaration:
`window.Popper = require('popper.js');`
not just 
`require('popper.js');`

**Comment by towfiles** [comment]
thank you all guys, the issue was with the popper compatibility

**Comment by surmaRahman** [comment]
I am having same problem..can you help me on that please? which version of bootstrap have you used
