### ISSUE TITLE
TypeError: 'querySelector' called on an object that does not implement interface Element.

### ISSUE THREAD

**Issue by jcoyne** [twbs/bootstrap#32368]
Versions:
MacOS 11.0.1
Firefox 83.0

This is using webpack 4.

I'm getting this error after upgrading from 5.0.0-alpha3 to -beta1. All worked fine in alpha3.
```
Uncaught TypeError: 'querySelector' called on an object that does not implement interface Element.
    findOne bootstrap.esm.js:965
    Modal bootstrap.esm.js:2564
    js bootstrap.esm.js:3103
    handler bootstrap.esm.js:369
    addHandler bootstrap.esm.js:448
    on bootstrap.esm.js:474
    js bootstrap.esm.js:3077
    Webpack 7
        __webpack_require__
        js
        __webpack_require__
        0
        __webpack_require__
        <anonymous>
        <anonymous>
```

**Comment by jcoyne** [comment]
This happened when I provided `data-bs-toggle` but did not provide `data-bs-target`
