### ISSUE TITLE
Tooltip does not work separately after Bootstrap v5.2.0 update

### ISSUE THREAD

**Issue by Aleksandr92Latvia** [twbs/bootstrap#37075]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I used tooltip.js from dist folder with all necessary imports. I used only part of bootstrap package.
After 5.2.0 update tooltip stopped work and console throw error "Uncaught TypeError: Popper__namespace.createPopper is not a function".

Looking at the code showed that Popper was defined as global["@popperjs/core"] in tooltip.js. (line 9)

factory(global["@popperjs/core"], global.Index, global.Sanitizer, global.EventHandler, global.Manipulator, global.BaseComponent, global.TemplateFactory)

In @popperjs/core package Popper is defined as global.Popper in @popperjs\core\dist\umd\popper.js (line 8)
factory(global.Popper = {}))

In bootstrap.min.js same Popper  is declarated as global.Popper and it still is working correctly.
Problem was fixed localy in my project by adding window["@popperjs/core"]=window.Popper

In same way Popper is added in dropdown.js

### Reduced test cases

https://codepen.io/Alexander92Latvia-Rez/pen/RwywgaV?editors=1111
Local fix was commented.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge, Opera

### What version of Bootstrap are you using?

v5.2.0

**Comment by mdo** [comment]
If you're importing the JS right in the browser, you need to read up on https://getbootstrap.com/docs/5.2/getting-started/javascript/#using-bootstrap-as-a-module. I'd suggest using a basic bundler if you can, but the link here will help some. https://github.com/twbs/bootstrap/pull/36854 may also address this.
